run_name: Bayes_1024_500e_Naive
run_folder: ttbar_third_cfm

method: GenerativeUnfolding

process: TTBarGenerative_v2
process_params:
  train_slice: [0., 0.8]
  val_slice: [0.8, 0.85]
  test_slice: [0.85, 1.0]
  training_file: "data/ttbar_full_10m.h5"
  analysis_file: "data/ttbar_full_10m.h5"
  enforce_2_bjets: True

# Preprocessing
hard_preprocessing:
  #type: ttbar_massparam
  #type: ttbar_naive_hard
  type: ttbar_naive_hard
  log: True
  erf_phi: False
  drop_masses: True
reco_preprocessing:
  type: ttbar_naive_reco
  log: True

# Training
lr: 1.e-3
batch_size: 16384
batch_size_sample: 10000
lr_scheduler: cosine_annealing
weight_decay: 0.
betas: [0.9, 0.99]
epochs: 500
use_ema: False
use_ema_sample: False

# Architecture
model: CFM
bayesian: True
bayesian_mode: "all"
bayesian_samples: 5
bayesian_factor: 1

latent_space: gaussian
#uniform_channels: [4]
#uniform_bounds: [0., 1.]
minimum_noise_scale: 0
t_noise_scale: 0

network_params:
  network_class: Subnet
  internal_size: 1024
  layers_per_block: 8
  activation: SiLU

  embed_t: True
  embed_t_mode: gfprojection
  embed_t_dim: 64

  embed_c: False
  embed_c_dim: 32
  embed_c_params:
    internal_size: 64
    layers_per_block: 4
    activation: SiLU

  embed_x: False
  embed_x_dim: 32
  embed_x_params:
    internal_size: 64
    layers_per_block: 4
    activation: SiLU

solver: ODE
solver_params:
  t_min: 0
  t_max: 1
  mixed_precision: False
  sde_method: srk
  ode_method: dopri5
  atol: 1.e-5
  rtol: 1.e-5
  step_size: 1.e-2

dist_samples_per_event: 2
n_unfoldings: 1
evaluate_train: False
evaluate_analysis: False
evaluate_comparison: False
plot_metrics: True