run_name: 8k_net_example
run_folder: INN/rqs

method: GenerativeUnfolding
process_params:
  train_slice: [0., 0.6]
  val_slice: [0.6, 0.65]
  test_slice: [0.65, 1.0]
  training_file: "data/Pythia26_full.npz"
  analysis_file: "data/Herwig_full.npz"

# Preprocessing
hard_preprocessing:
  type:
  unit_hypercube: False
  args:
    pt_conserved: True
reco_preprocessing:
  type:

# Training
lr: 1.e-4
max_lr: 5.e-4
batch_size: 128
lr_scheduler: one_cycle
weight_decay: 0.
betas: [0.9, 0.999]
epochs: 50

# Architecture
model: INN
latent_space: uniform
uniform_bounds: [0., 1.]

n_blocks: 6
internal_size: 16
layers_per_block: 3
coupling_type: rational_quadratic
permute_soft: False
num_bins: 6
dropout: 0.0

evaluate_train: False
evaluate_analysis: False
