run_name: test #permute_False-8_blocks-4_layers-20_wide-6_bins-uniform_latent-cosine_annealing-40_epochs
run_folder: INN/RQS

method: GenerativeUnfolding
process_params:
  train_slice: [0., 0.6]
  val_slice: [0.6, 0.65]
  test_slice: [0.65, 1.0]
  training_file: "data/Pythia26_full.npz"
  analysis_file: "data/Herwig_full.npz"

# Preprocessing
hard_preprocessing:
  type:
  unit_hypercube: False
  sigmoid_norm: True
  args:
    pt_conserved: True
reco_preprocessing:
  type:
  unit_hypercube: False
  sigmoid_norm: True

# Training
lr: 1.e-3
max_lr: 5.e-4
batch_size: 128
lr_scheduler: cosine_annealing
weight_decay: 0.
betas: [0.9, 0.999]
epochs: 2

# Architecture
model: INN
latent_space: uniform
uniform_bounds: [0., 1.]

n_blocks: 8
internal_size: 20
layers_per_block: 4
coupling_type: rational_quadratic
permute_soft: False
num_bins: 6
dropout: 0.0

evaluate_train: True
evaluate_analysis: True
evaluate_best: True
