run_name: one_tenth_dataset-300epochs-loader_theirs
run_folder: Omnifold

method: Omnifold

process: ZJetsOmnifold
process_params:
  loader: theirs
  train_slice: [0., 0.06]
  val_slice: [0.06, 0.1]
  test_slice: [0.65, 1.0]
  training_file: "data/Pythia26_full.npz"
  analysis_file: "data/Herwig_full.npz"

# Preprocessing
hard_preprocessing:
  uniform_noise_channels: []
reco_preprocessing:
  uniform_noise_channels: []

# Training
lr: 1.e-3
max_lr: 3.e-4
batch_size: 128
lr_scheduler: cosine_annealing
weight_decay: 0.
betas: [0.9, 0.999]
epochs: 300


# Architecture
model: Classifier
bayesian: False
bayesian_samples: 20

internal_size: 80
layers_per_block: 4
dropout: 0.0

evaluate_train: True
