run_name: bOmnifold_03datasplit_100e_256dim
run_folder: Omnifold

method: Omnifold

process: ZJetsOmnifold
process_params:
  train_slice: [0., 0.3]
  val_slice: [0.6, 0.65]
  test_slice: [0.65, 1.0]
  training_file: "data/Pythia26_full.npz"
  analysis_file: "data/Herwig_full.npz"

# Preprocessing
hard_preprocessing:
  uniform_noise_channels: []
  erf_norm: False
reco_preprocessing:
  uniform_noise_channels: []
  erf_norm: False

# Training
lr: 1.e-3
max_lr: 3.e-4
batch_size: 128
lr_scheduler: cosine_annealing
weight_decay: 0.
betas: [0.9, 0.999]
epochs: 100

# Architecture
model: Classifier
bayesian: True
bayesian_samples: 20

internal_size: 256
layers_per_block: 4
dropout: 0.0

evaluate_train: False
