run_name: test
run_folder: Omnifold

method: Omnifold
process: ZJetsOmnifold
process_params:
  train_slice: [0., 0.6]
  val_slice: [0.6, 0.65]
  test_slice: [0.65, 1.0]
  training_file: "data/Pythia26_full.npz"
  analysis_file: "data/Herwig_full.npz"

# Preprocessing
hard_preprocessing:
  type:
  unit_hypercube: False
  args:
    pt_conserved: True
reco_preprocessing:
  type:

# Training
lr: 1.e-4
max_lr: 3.e-4
batch_size: 128
lr_scheduler: cosine_annealing
weight_decay: 0.
betas: [0.9, 0.999]
epochs: 30

# Architecture
model: Classifier

internal_size: 256
layers_per_block: 5
dropout: 0.0

evaluate_train: False
