run_name: TraCFM_naive_256d_800e_OC
run_folder: ttbar_second

method: GenerativeUnfolding

process: TTBarGenerative
process_params:
  train_slice: [0., 0.7]
  val_slice: [0.7, 0.75]
  test_slice: [0.75, 1.0]
  training_file: "data/ttbar_full.h5"
  analysis_file: "data/ttbar_full.h5"

# Preprocessing
hard_preprocessing:
  type: ttbar_naive_hard
  log: False
reco_preprocessing:
  type: ttbar_naive_reco
  log: False

# Training
lr: 1.e-3
max_lr: 1.e-3
batch_size: 4096
batch_size_sample: 10000
lr_scheduler: one_cycle
weight_decay: 0.
betas: [0.9, 0.99]
epochs: 800
use_ema: True
use_ema_sample: True

# Architecture
model: CFMwithTransformer
bayesian: False

latent_space: gaussian
minimum_noise_scale: 0
t_noise_scale: 0


dropout: 0.0
dim_embedding: 256
n_head: 4
n_encoder_layers: 6
n_decoder_layers: 6
dim_feedforward: 512
embedding_nets: False

network_params:
  network_class: Subnet
  internal_size: 76
  layers_per_block: 4
  activation: SiLU

  embed_t: False
  embed_t_mode: gfprojection
  embed_t_dim: 16

solver: ODE
solver_params:
  t_min: 0
  t_max: 1
  mixed_precision: False
  sde_method: srk
  ode_method: dopri5
  atol: 1.e-5
  rtol: 1.e-5
  step_size: 1.e-2

dist_samples_per_event: 2
n_unfoldings: 5
evaluate_train: True
evaluate_analysis: False
evaluate_comparison: False
plot_metrics: True