run_name: transfermer_naive_dropM_2b_400e_TracfmSetup
run_folder: ttbar_second

method: GenerativeUnfolding

process: TTBarGenerative
process_params:
  train_slice: [0., 0.7]
  val_slice: [0.7, 0.75]
  test_slice: [0.75, 1.0]
  training_file: "data/ttbar_full.h5"
  analysis_file: "data/ttbar_full.h5"
  enforce_2_bjets: False

# Preprocessing
hard_preprocessing:
  type: ttbar_naive_hard
  drop_masses: True
  log: False
reco_preprocessing:
  type: ttbar_naive_reco
  log: False

# Training
lr: 1.e-3
max_lr: 3.e-4
batch_size: 1024
batch_size_sample: 10000
lr_scheduler: one_cycle
weight_decay: 0.
betas: [0.9, 0.99]
epochs: 400

# Architecture
model: Transfermer1d
bayesian: False

dropout: 0.0
dim_embedding: 128
n_head: 4
n_encoder_layers: 6
n_decoder_layers: 6
dim_feedforward: 512
embedding_nets: False

internal_size: 256
layers_per_block: 5
num_bins: 30

dist_samples_per_event: 2
n_unfoldings: 5
evaluate_train: False
evaluate_analysis: False
evaluate_comparison: False
plot_metrics: True