run_name: reproduce
run_folder: cINN/affine

process: thj_lo
process_params:
  train_slice: [0., 0.6]
  val_slice: [0.6, 0.65]
  test_slice: [0.65, 1.0]
  training_file: "data/Pythia26_full.npz"
  analysis_file: "data/Herwig_full.npz"

# Preprocessing
hard_preprocessing:
  type:
  args:
    pt_conserved: True
reco_preprocessing:
  type:

# Training
lr: 1.e-3
max_lr: 3.e-4
batch_size: 124
lr_scheduler: None
weight_decay: 0.
betas: [0.9, 0.999]
epochs: 30

# Architecture
model: INN
latent_space: gaussian
uniform_channels: [5]
uniform_bounds: [-1., 1.]
add_noise: False
add_noise_scale: 1.e-5


n_blocks: 6
internal_size: 40
layers_per_block: 3
coupling_type: affine
permute_soft: True
num_bins: 10
dropout: 0.0

evaluate_train: False
evaluate_analysis: False
