run_name: inn_unfold_transfer

process: thj_lo
process_params:
  train_slice: [0.480, 0.5]
  val_slice: [0.54, 0.55]
  test_slice: [0.985, 1.0]
  training_file: "data/cp_vio_yukawa_leptonic_sampled.h5"
  max_reco_momenta: 5
  final_state: leptonic


# Preprocessing
hard_preprocessing:
  type: momentum
  args:
    pt_conserved: True
reco_preprocessing:
  type: momentum
alpha_preprocessing:
  type: scale
  args:
    factors: [0.005555] # = 1/180

# Training
lr: 1.e-4
max_lr: 3.e-4
batch_size: 1024
lr_scheduler: one_cycle
weight_decay: 0.
betas: [0.9, 0.999]
epochs: 1

# Architecture
n_blocks: 2
internal_size: 256
layers_per_block: 5
coupling_type: rational_quadratic
permute_soft: True
num_bins: 30
dropout: 0.0

